apiVersion: v1
kind: Service
metadata:
  name: verify-ca-service
  labels: { component: verify, type: ca }
spec:
  type: ClusterIP
  selector:
    component: verify
    type: ca
  ports:
    - port: 7054
      targetPort: 7054
