apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer1-verify-couchdb-deployment
  labels: { component: peer1, type: couchdb, org: verify }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: peer1
      type: couchdb
      org: verify
  template:
    metadata:
      labels:
        component: peer1
        type: couchdb
        org: verify
    spec:
      volumes:
        - name: my-pv-storage
          persistentVolumeClaim:
            claimName: my-pv-claim
      containers:
        - name: peer1-verify-couchdb
          image: couchdb:3.1.1
          env:
            - name: COUCHDB_USER
              value: nick
            - name: COUCHDB_PASSWORD
              value: "1234"
          volumeMounts:
            - mountPath: /opt/couchdb/data
              name: my-pv-storage
              subPath: state/verify/peers/peer1-couchdb
