export const RESET_ALL_STATE = 'RESET_ALL_STATE';
export const DOCUMENT_TYPE = 'DOCUMENT_TYPE';
export const DOCUMENT_FRONT_IMAGE = 'DOCUMENT_FRONT_IMAGE';
export const DOCUMENT_BACK_IMAGE = 'DOCUMENT_BACK_IMAGE';
export const TEXTRACT_TEXT = 'TEXTRACT_TEXT';
export const RESET_UPLOAD_STATE = 'RESET_UPLOAD_STATE';
