apiVersion: v1
kind: Service
metadata:
  name: fabric-be-service
spec:
  selector:
    app: node-app 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 4000
    nodePort: 31110
